"""Summarize generated-reasoning training evaluation against unchanged rollout tests."""
import json,html
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'analysis_results/move_only_500';DATA=OUT/'generated_training'
NAMES={'pretrained':'Original MiniVLA','lambda1':'Round 3 λ=1','moveonly':'Mismatch only'}
old=json.loads((OUT/'stop_and_execution_analysis.json').read_text())
test_keys={'pretrained':'pretrained','lambda1':'Round 3 lambda 1, 200 steps','moveonly':'Mismatch only, 500 steps'}
manifest=json.loads((ROOT/'runs/ecot-move-alignment/round3-ecot-lite-libero90-hinge-lora-r16-lambda10-seed20261102/split_manifest.json').read_text())
expected=set(manifest['train_ids'])
result={'method':'autogenerated reasoning and discrete VQ action codes; exact rollout BF16 checkpoint loading and inference path; fixed training images','models':{}}
for model in NAMES:
 rows=[]
 for path in sorted(DATA.glob(f'{model}-rank*.jsonl')):
  lines=path.read_text().splitlines()
  for i,line in enumerate(lines):
   try:rows.append(json.loads(line))
   except json.JSONDecodeError:
    if i!=len(lines)-1:raise
 ids=[r['record_id'] for r in rows];assert len(set(ids))==len(ids);assert set(ids)<=expected
 d={'evaluated':len(rows),'complete':set(ids)==expected,'training':{},'test':old['test'][test_keys[model]]['euclidean']}
 for name,success in [('overall',None),('successful',True),('failed',False)]:
  allrows=[r for r in rows if success is None or r['source_episode_success']==success]
  group=[r for r in allrows if r['included']]
  k=sum(r['mismatch'] for r in group);n=len(group)
  d['training'][name]={'queries':n,'mismatches':k,'percent':100*k/n if n else None,'excluded':len(allrows)-n,'stop_queries':sum(r['stop'] for r in group),'directional_queries':sum(r['directional'] for r in group)}
 d['test']=dict(d['test'])
 n=sum(v['queries'] for v in d['test'].values());k=sum(v['mismatches'] for v in d['test'].values())
 d['test']['overall']={'queries':n,'mismatches':k,'percent':100*k/n}
 result['models'][model]=d
result['complete']=all(d['complete'] for d in result['models'].values())
text=['<h1>Generated reasoning and discrete-action evaluation</h1>',
'<p>Inference only: frozen original MiniVLA, Round 3 λ=1 (200 steps), mismatch-only (500 steps). All models receive each of the same 1,245 training images and its task instruction, generate their own reasoning, and autoregressively generate discrete VQ action tokens. No saved reasoning or target action tokens are supplied. Checkpoint loading, BF16, image preprocessing, and generation match the existing rollout evaluation.</p>',
'<p>Directional mismatch: cosine &lt; 0.5 against the generated reasoning. Literal MOVE: stop mismatch: norm of sum(0.05 × clip(action_xyz,−1,1)) &gt; 0.03 m over ten commands. Other zero-vector claims are excluded and their counts reported below. Denominators can change because each model now generates its own reasoning. This evaluates internal reasoning–command consistency, not correctness of the reasoning relative to the task.</p>',
'<p>Training outcomes refer to the fixed source episodes. Test outcomes refer to each model’s existing 180 rollouts. Generation procedures now match; observation distributions still differ. Test task-success numbers are unchanged.</p>',
'<table><tr><th>Policy-command mismatch</th>'+''.join('<th>'+n+'</th>' for n in NAMES.values())+'</tr>']
for split in ['training','test']:
 for outcome in ['overall','successful','failed']:
  text.append('<tr><th>'+split.title()+' — '+outcome+'</th>')
  for d in result['models'].values():
   x=d[split][outcome]
   value=f"{x['percent']:.2f}% ({x['mismatches']}/{x['queries']:,})" if split=='test' or d['complete'] else f"Pending: {d['evaluated']}/1,245 images"
   text.append('<td>'+value+'</td>')
  text.append('</tr>')
text.append('<tr><th>Test task success</th><td>86.7%</td><td>90.0%</td><td>88.9%</td></tr></table>')
text.append('<h2>Training generation coverage</h2><table><tr><th>Model</th><th>Images evaluated</th><th>Directional</th><th>Literal stop</th><th>Excluded</th></tr>')
for model,d in result['models'].items():
 x=d['training']['overall'];text.append(f"<tr><td>{NAMES[model]}</td><td>{d['evaluated']}</td><td>{x['directional_queries']}</td><td>{x['stop_queries']}</td><td>{x['excluded']}</td></tr>")
text.append('</table><p><a href="index.html">Previous soft-decoded analysis</a></p>')
(OUT/'generated_training_comparison.json').write_text(json.dumps(result,indent=2)+'\n')
p=OUT/'generated_training.html';tmp=p.with_suffix('.tmp');tmp.write_text('<!doctype html><meta charset="utf-8"><title>Generated training evaluation</title><style>body{font:16px system-ui;max-width:1400px;margin:32px auto;padding:20px;color:#193653}td,th{padding:10px;border:1px solid #ccc}table{border-collapse:collapse}th{background:#e8eef4}</style>'+''.join(text));tmp.replace(p)
print(json.dumps({k:{'evaluated':v['evaluated'],'training':v['training']} for k,v in result['models'].items()},indent=2))
